sonar.projectKey=anastasijica_ecommerceShopWatch
sonar.projectName=eCommerceShopWatch
sonar.projectVersion=1.0.0
sonar.organization=anastasijica

# Sources
sonar.sources=services/user-service/src,services/product-service/src,services/order-service/src,services/notification-service/src,services/api-gateway/src
sonar.tests=services/user-service/src,services/product-service/src,services/order-service/src,services/notification-service/src,services/user-service/test,services/product-service/test,services/order-service/test,services/notification-service/test

sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,frontend/**

sonar.typescript.lcov.reportPaths=services/user-service/coverage/lcov.info,services/product-service/coverage/lcov.info,services/order-service/coverage/lcov.info,services/notification-service/coverage/lcov.info

sonar.sourceEncoding=UTF-8
