const categories = [
  { id: 'watches', name: 'Satovi' },
  { id: 'necklaces', name: 'Ogrlice' },
  { id: 'rings', name: 'Prstenje' },
  { id: 'bracelets', name: 'Narukvice' },
  { id: 'earrings', name: 'Minđuše' },
];

const mockProducts = [
  {
    id: 'watch-001',
    name: 'Klasični Dvobojni Ručni Sat',
    description: 'Elegantan muški ručni sat sa dvobojnom (zlatnom i srebrnom) Jubilee narukvicom, fluted bezelom i belim ciferblatom sa datumom. Savršen za svaku priliku.',
    price: 75000,
    stock: 15,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop&crop=center',
    category: 'watches',
    createdAt: new Date(),
  },
  {
    id: 'watch-002',
    name: 'Sportski Hronograf Sat',
    description: 'Robusan sportski sat sa funkcijom hronografa, crnim ciferblatom i silikonskom narukvicom. Vodootporan do 100m.',
    price: 45000,
    stock: 22,
    imageUrl: 'https://images.unsplash.com/photo-1523170335258-f5c6a6f1c0c7?w=400&h=300&fit=crop&crop=center',
    category: 'watches',
    createdAt: new Date(),
  },
  {
    id: 'watch-003',
    name: 'Minimalistički Ženski Sat',
    description: 'Tanak i elegantan ženski sat sa mrežastom narukvicom i minimalističkim ciferblatom. Rose gold boja.',
    price: 32000,
    stock: 18,
    imageUrl: 'https://images.unsplash.com/photo-1594534475808-b18fc33b045e?w=400&h=300&fit=crop&crop=center',
    category: 'watches',
    createdAt: new Date(),
  },
  {
    id: 'watch-004',
    name: 'Luksuzni Zlatni Sat',
    description: 'Prestižni zlatni sat sa dijamantskim markerima, fluted bezelom i datumom. Rose gold kućište sa zlatnom narukvicom.',
    price: 125000,
    stock: 8,
    imageUrl: 'https://images.unsplash.com/photo-1551816230-ef5deaed4a26?w=400&h=300&fit=crop&crop=center',
    category: 'watches',
    createdAt: new Date(),
  },
  {
    id: 'necklace-001',
    name: 'Srebrna Ogrlica sa Priveskom',
    description: 'Delikatna srebrna ogrlica sa elegantnim priveskom od cirkona. Idealan poklon za posebne prilike.',
    price: 12000,
    stock: 30,
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&h=300&fit=crop&crop=center',
    category: 'necklaces',
    createdAt: new Date(),
  },
  {
    id: 'necklace-002',
    name: 'Zlatna Ogrlica sa Inicijalom',
    description: 'Personalizovana zlatna ogrlica sa priveskom u obliku inicijala. Izaberite svoje slovo.',
    price: 18000,
    stock: 20,
    imageUrl: 'https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400&h=300&fit=crop&crop=center',
    category: 'necklaces',
    createdAt: new Date(),
  },
  {
    id: 'ring-001',
    name: 'Zlatni Prsten sa Dijamantom',
    description: 'Prelepi zlatni prsten sa centralnim dijamantom i manjim dijamantima sa strane. Savršen za veridbu.',
    price: 250000,
    stock: 5,
    imageUrl: 'https://images.unsplash.com/photo-1605100804763-247f67b3557e?w=400&h=300&fit=crop&crop=center',
    category: 'rings',
    createdAt: new Date(),
  },
  {
    id: 'ring-002',
    name: 'Srebrni Prsten sa Cirkonom',
    description: 'Elegantan srebrni prsten sa centralnim cirkonom i manjim kristalima. Unisex dizajn.',
    price: 8500,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1603561591411-07134e71a2a9?w=400&h=300&fit=crop&crop=center',
    category: 'rings',
    createdAt: new Date(),
  },
  {
    id: 'bracelet-001',
    name: 'Kožna Narukvica sa Srebrnim Detaljima',
    description: 'Moderna kožna narukvica sa ukrasnim srebrnim kopčama. Unisex dizajn.',
    price: 8000,
    stock: 40,
    imageUrl: 'https://images.unsplash.com/photo-1617038220319-276d4f7d2b0b?w=400&h=300&fit=crop&crop=center',
    category: 'bracelets',
    createdAt: new Date(),
  },
  {
    id: 'bracelet-002',
    name: 'Zlatna Narukvica sa Linkovima',
    description: 'Klasična zlatna narukvica sa tankim linkovima. Elegantan dodatak za svaku priliku.',
    price: 15000,
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&h=300&fit=crop&crop=center',
    category: 'bracelets',
    createdAt: new Date(),
  },
  {
    id: 'earrings-001',
    name: 'Biserne Minđuše',
    description: 'Klasične biserne minđuše sa srebrnim kopčama. Elegantan dodatak za svaku damu.',
    price: 9500,
    stock: 25,
    imageUrl: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=300&fit=crop&crop=center',
    category: 'earrings',
    createdAt: new Date(),
  },
  {
    id: 'earrings-002',
    name: 'Zlatne Minđuše sa Dijamantima',
    description: 'Luksuzne zlatne minđuše sa malim dijamantima. Savršene za posebne prilike.',
    price: 35000,
    stock: 12,
    imageUrl: 'https://images.unsplash.com/photo-1506630448388-4e683c67ddb0?w=400&h=300&fit=crop&crop=center',
    category: 'earrings',
    createdAt: new Date(),
  },
];

// CommonJS exports
module.exports = {
  categories,
  mockProducts
};
